--FiveM's list of Ped Models can be found here: https://docs.fivem.net/docs/game-references/ped-models/
--A list of all the animations can be found here: https://alexguirre.github.io/animations-list/

Config = {}
Config.Invincible = true --Do you want the peds to be invincible?
Config.Frozen = true --Do you want the peds to be unable to move? It's probably a yes, so leave true in there.
Config.Stoic = true --Do you want the peds to react to what is happening in their surroundings?
Config.Fade = true-- Do you want the peds to fade into/out of existence? It looks better than just *POP* its there.
Config.Distance = 50.0 --The distance you want peds to spawn at

--Does the system you use for grabbing coordinates require subracting from the z axis?
--If so, set this to true. You'll have to adjust the coordinates for defaults down - 1 if you set false.
Config.MinusOne = true

Config.PedList = {
	-- Hand Security
	{
		model = "csb_vagspeak",
		coords = vector3(526.91, -2763.73, 6.64),
		heading = 268.83,
		gender = "male",
		animDict = "anim@heists@heist_corona@single_team",
		animName = "single_team_loop_boss",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "csb_vagspeak",
		coords = vector3(528.27, -2761.47, 6.64),
		heading = 224.48,
		gender = "male",
		animDict = "anim@heists@heist_corona@single_team",
		animName = "single_team_loop_boss",
		isRendered = false,	
        ped = nil,
	},

	-- Computer Engineer
	{
		model = "csb_chin_goon",
		coords = vector3(542.88, -2767.43, 6.04),
		heading = 241.09,
		gender = "male",
		animDict = "mini@repair",
		animName = "fixing_a_ped",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "cs_movpremmale",
		coords = vector3(542.65, -2766.38, 6.04),
		heading = 234.79,
		gender = "male",
		scenario = "WORLD_HUMAN_CLIPBOARD",
		isRendered = false,	
        ped = nil,
	},

	-- Gun Security
	{
		model = "mp_m_securoguard_01",
		coords = vector3(538.33, -2781.2, 6.04),
		heading = 57.69,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(537.53, -2782.71, 6.04),
		heading = 50.76,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(506.0, -2769.53, 6.03),
		heading = 62.98,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(512.66, -2758.77, 6.03),
		heading = 62.82,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(515.31, -2754.16, 6.03),
		heading = 62.14,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(517.55, -2750.3, 6.03),
		heading = 58.16,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(487.51, -2741.64, 3.07),
		heading = 242.53,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(482.84, -2749.11, 3.07),
		heading = 238.85,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(507.07, -2754.13, 3.07),
		heading = 62.77,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(506.36, -2751.7, 3.07),
		heading = 118.34,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(503.37, -2759.17, 3.07),
		heading = 19.11,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(563.48, -2781.73, 6.04),
		heading = 146.35,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(555.57, -2777.23, 6.05),
		heading = 152.19,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(561.33, -2790.76, 6.1),
		heading = 146.08,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(560.06, -2792.97, 6.1),
		heading = 326.87,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(553.21, -2788.65, 6.1),
		heading = 327.11,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(554.32, -2786.6, 6.1),
		heading = 149.59,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(541.65, -2780.72, 6.1),
		heading = 241.12,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(552.56, -2781.77, 6.1),
		heading = 153.02,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(547.87, -2772.67, 6.05),
		heading = 151.32,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(546.09, -2775.72, 6.05),
		heading = 330.68,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
	{
		model = "mp_m_securoguard_01",
		coords = vector3(553.78, -2780.3, 6.04),
		heading = 327.88,
		gender = "male",
		gun = "weapon_assaultrifle",
		isRendered = false,	
        ped = nil,
	},
}